--------------------------------------------------------
--  Constraints for Table DBTOOLS$EXECUTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "ODI_WS"."DBTOOLS$EXECUTION_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODI_WS"."DBTOOLS$EXECUTION_HISTORY" ADD CONSTRAINT "DBTOOLS$EXECUTION_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
