--------------------------------------------------------
--  DDL for Index DBTOOLS$EXECUTION_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODI_WS"."DBTOOLS$EXECUTION_HISTORY_PK" ON "ODI_WS"."DBTOOLS$EXECUTION_HISTORY" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
