--------------------------------------------------------
--  DDL for Table EMP_STG_DEDUCTIONS
--------------------------------------------------------

  CREATE TABLE "ODI_WS"."EMP_STG_DEDUCTIONS" 
   (	"UNIQEBATCHID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMPID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LOANB1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRINCIPAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEREST" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSTATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATED" TIMESTAMP (6) DEFAULT systimestamp
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
