--------------------------------------------------------
--  DDL for Sequence DBTOOLS$EXECUTION_HISTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ODI_WS"."DBTOOLS$EXECUTION_HISTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
