--------------------------------------------------------
--  DDL for Table EMP_STG_SALARY
--------------------------------------------------------

  CREATE TABLE "ODI_WS"."EMP_STG_SALARY" 
   (	"UNIQEBATCHID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SALARYDATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COMPANY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMPID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BASIC" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"HRA" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MEDICAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SPECIALALLOW" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"OTHERALLOW" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEPHONEREM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVEYANCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATED" TIMESTAMP (6) DEFAULT systimestamp
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
